(()=>{
const KEY='after-school-lectia-2-v1', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], steps=['story','quiz','traits','quality','wish','fear','dialogues','portrait'];
const story=['Luca își deschise ideea de poveste de la lecția trecută: „Un roboțel găsește o ușă secretă într-o pădure.”','— Am o idee! Dar cine este acest roboțel? se întrebă el.','Atunci, pe ecran apăru o oglindă magică.','— Un personaj bun nu este doar un nume. Trebuie să știi ce îi place, ce își dorește, de ce îi este frică și cum reacționează.','Luca începu să-l construiască:','🤖 Max era curios, dar îi era teamă de întuneric. Își dorea să descopere locuri necunoscute.','— Acum Max pare adevărat! spuse Luca.'];
const quiz=[['Ce personaj avea Luca în povestea lui?',['Un dragon','Un roboțel','O pisică'],1],['Cum îl chema pe roboțel?',['Alex','Max','Luca'],1],['Cum era Max?',['Trist și leneș','Curios, dar îi era teamă de întuneric','Furios și nepoliticos'],1],['Ce își dorea Max?',['Să devină profesor','Să descopere locuri necunoscute','Să construiască o casă'],1],['Ce face un personaj interesant?',['Doar hainele lui','Doar numele lui','Personalitatea, dorințele, emoțiile și temerile lui'],2]];
const traits=['Curajos','Curios','Amuzant','Timid','Generos','Încăpățânat','Fricos','Neatent','Bun','Răutăcios','Inteligent','Nerăbdător'];
const sort=[['Curajos','good'],['Generos','good'],['Atent','good'],['Prietenos','good'],['Curios','good'],['Răbdător','good'],['Încăpățânat','bad'],['Nerăbdător','bad'],['Fricos','bad'],['Neatent','bad'],['Gelos','bad'],['Ușor de speriat','bad']];
const wishes=['Să găsească un prieten','Să descopere un secret','Să salveze pe cineva','Să câștige un concurs','Să găsească o comoară','Să ajungă într-un loc magic','Să demonstreze că poate face ceva','Să repare o greșeală'];
const fears=['Întuneric','Înălțimi','Singurătate','Să piardă pe cineva','Să greșească','Animale','Locuri necunoscute','Nu îi este frică de nimic'];
const dialogues=[['Mi-e teamă să intru în peșteră.','Și mie mi-e teamă, dar __________________.'],['Ce este în cutia aceasta?','Nu știu, dar aș vrea să __________________.'],['Nu pot să fac asta singur.','Nu ești singur. Eu __________________.'],['De ce ai venit la castel cu un ghiozdan?','Pentru că în ghiozdan am __________________!'],['Cine ești?','Sunt cel care __________________.']];
const guess=[['Este foarte curios, pune mereu întrebări și adoră să descopere lucruri noi.',['Timidul','Exploratorul','Leneșul'],1],['Îi este frică de întuneric, dar intră în peșteră când prietenul are nevoie.',['Fricosul','Curajosul','Leneșul'],1],['Își împarte lucrurile cu ceilalți și sare imediat în ajutor.',['Generosul','Egoistul','Neatentul'],0]];
  const state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{quiz:[],traits:[],sort:{},wish:'',wishText:'',fear:'',fearText:'',dialogues:Array(5).fill(''),portrait:{}}}catch{return {quiz:[],traits:[],sort:{},wish:'',wishText:'',fear:'',fearText:'',dialogues:Array(5).fill(''),portrait:{}}}})();
  state.verify=Object.assign({quiz:false,sort:false,guess:false},state.verify||{});
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}; const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function choices(id,items,selected,multi=true){$(id).innerHTML=items.map((x,i)=>`<label class="choice"><input type="${multi?'checkbox':'radio'}" name="${id.slice(1)}" value="${i}" ${multi?(selected||[]).includes(i)?'checked':'':Number(selected)===i?'checked':''}><span>${esc(x)}</span></label>`).join('')}
function feedback(id,msg,type='success'){const e=$(id);e.textContent=msg;e.className='feedback '+(msg?type:'')}
  function render(){
    $('#story').innerHTML=story.map((x,i)=>`<p class="${x.startsWith('—')?'dialogue':''} ${i===5?'highlight':''}">${esc(x)}</p>`).join('');
    $('#quizList').innerHTML=quiz.map((q,i)=>{
      const selected=state.quiz[i], verified=!!state.verify.quiz;
      const options=q[1].map((o,j)=>`<label class="choice ${verified && (selected===j || j===q[2]) ? (j===q[2]?'is-correct':'is-wrong') : ''} ${verified && j===q[2] && selected!==q[2]?'correct-answer':''}"><input type="radio" name="q${i}" value="${j}" ${selected===j?'checked':''}><span>${String.fromCharCode(97+j)}) ${esc(o)}</span>${verified && j===q[2]?'<span class="answer-mark" aria-label="răspuns corect">✓</span>':verified && selected===j?'<span class="answer-mark" aria-label="răspuns greșit">✕</span>':''}</label>`).join('');
      const explanation=verified ? `<div class="answer-explanation ${selected===q[2]?'good':'bad'}">${selected==null?`⚠️ Nu ai ales. Răspunsul corect este: <strong>${esc(q[1][q[2]])}</strong>.`:selected===q[2]?'✅ Corect!':`❌ Ai ales „${esc(q[1][selected])}”. Răspunsul corect este: <strong>${esc(q[1][q[2]])}</strong>.`}</div>` : '';
      return `<div class="question-card"><fieldset><legend>${i+1}. ${esc(q[0])}</legend>${options}${explanation}</fieldset></div>`;
    }).join('');
    choices('#traitsChoices',traits,state.traits); $('#traitsCount').textContent=`Ai ales ${state.traits.length} din 3–5.`; $('#traitsResult').textContent=state.traits.length?`Personajul tău este: ${state.traits.map(i=>traits[i]).join(', ')}.`:''; choices('#wishChoices',wishes,wishes.indexOf(state.wish),false); $('#wishText').value=state.wishText||''; choices('#fearChoices',fears,fears.indexOf(state.fear),false); $('#fearText').value=state.fearText||''; $('#dialogueList').innerHTML=dialogues.map((d,i)=>`<div class="dialogue-card"><strong>Dialogul ${i+1}</strong><p>— „${esc(d[0])}”<br>— „${esc(d[1])}”</p><textarea data-dialogue="${i}" rows="3" placeholder="Completează replica...">${esc(state.dialogues[i]||'')}</textarea></div>`).join(''); renderSort(); renderPortrait();
    if(state.verify.quiz){const score=quiz.reduce((s,q,i)=>s+(state.quiz[i]===q[2]?1:0),0);feedback('#quizFeedback',`Ai ${score} din ${quiz.length} răspunsuri corecte. ${score===quiz.length?'🎉 Toate sunt corecte!':'Răspunsurile verzi sunt corecte; cele roșii au explicația dedesubt.'}`,score===quiz.length?'success':'error');} else feedback('#quizFeedback','');
  }
  function renderSort(){ $('#traitsBank').innerHTML=sort.filter(([x])=>!state.sort[x]).map(([x])=>`<button class="drop-item" type="button" draggable="true" data-trait="${esc(x)}">${esc(x)}</button>`).join(''); $$('.drop-zone').forEach(z=>z.querySelector('.drop-items').innerHTML=''); Object.entries(state.sort).forEach(([x,zone])=>{const z=$(`[data-zone="${zone}"] .drop-items`);if(z){const expected=sort.find(item=>item[0]===x)?.[1];const cls=state.verify.sort?(expected===zone?'is-correct':'is-wrong'):'';const mark=state.verify.sort?(expected===zone?' ✓':' ✕ · corect: '+(expected==='good'?'Calități':'Defecte')):'';z.insertAdjacentHTML('beforeend',`<button class="drop-item ${cls}" type="button" data-placed="${esc(x)}">${esc(x)}${mark}</button>`);}}); if(state.verify.sort){const score=sort.filter(([x,z])=>state.sort[x]===z).length;feedback('#qualityFeedback',`Ai sortat corect ${score}/${sort.length}. ${score===sort.length?'🎉 Excelent!':'Roșu = categorie greșită. Mută cartonașul și verifică din nou.'}`,score===sort.length?'success':'error');}}
  function renderPortrait(){const p=state.portrait||{}; $('#guessList').innerHTML=guess.map((g,i)=>{const selected=p['g'+i],verified=!!state.verify.guess;return `<div class="question-card"><p>${esc(g[0])}</p>${g[1].map((o,j)=>`<label class="choice ${verified && (selected===j || j===g[2])?(j===g[2]?'is-correct':'is-wrong'):''} ${verified && j===g[2] && selected!==g[2]?'correct-answer':''}"><input type="radio" name="guess${i}" value="${j}" ${selected===j?'checked':''}><span>${esc(o)}</span>${verified&&j===g[2]?'<span class="answer-mark">✓</span>':verified&&selected===j?'<span class="answer-mark">✕</span>':''}</label>`).join('')}${verified?`<div class="answer-explanation ${selected===g[2]?'good':'bad'}">${selected===g[2]?'✅ Corect!':`❌ Răspunsul corect este: <strong>${esc(g[1][g[2]])}</strong>.`}</div>`:''}</div>`;}).join(''); $('#guessList').insertAdjacentHTML('afterbegin','<button class="button button-primary verify-small" type="button" data-action="check-guess">Verifică ghiceala</button>'); choices('#kindChoices',['Copil','Animal','Robot','Creatură fantastică','Extraterestru','Personaj inventat'],p.kind,false); choices('#portraitTraits',['Curajos','Curios','Amuzant','Timid','Generos','Inteligent','Încăpățânat','Nerăbdător','Visător','Misterios'],p.traits||[]); choices('#likesChoices',['Aventurile','Animalele','Cărțile','Jocurile','Să exploreze','Să inventeze lucruri','Să ajute oamenii','Altceva'],p.like,false); choices('#portraitFear',fears.slice(0,7).concat(['Altceva']),p.pfear,false); $('#name').value=p.name||'';$('#likesOther').value=p.other||'';$('#bigWish').value=p.bigWish||''; summary(); if(state.verify.guess){const score=guess.filter((g,i)=>p['g'+i]===g[2]).length;feedback('#guessFeedback',`Ai ${score}/${guess.length} răspunsuri corecte. ${score===guess.length?'🎉':'Răspunsurile corecte sunt marcate cu verde.'}`,score===guess.length?'success':'error');}else feedback('#guessFeedback','');}
function summary(){const p=state.portrait||{};if(!p.name&&!p.kind)return $('#portraitSummary').textContent='Completează portretul, iar rezumatul apare aici.';$('#portraitSummary').textContent=`${p.name||'Personajul'} este ${p.kind||'un personaj'}${p.traits?.length?' — '+p.traits.map(i=>['Curajos','Curios','Amuzant','Timid','Generos','Inteligent','Încăpățânat','Nerăbdător','Visător','Misterios'][i]).join(', '):''}. Îi place ${p.like||'să descopere lumea'} și își dorește ${p.bigWish||'ceva important'}.`;}
function show(step,push=true){if(!steps.includes(step))step='story';$$('[data-step-panel]').forEach(e=>{e.hidden=e.dataset.stepPanel!==step;e.classList.toggle('is-active',e.dataset.stepPanel===step)});$$('.step-link').forEach(e=>e.classList.toggle('is-active',e.dataset.step===step));const n=steps.indexOf(step)+1;$('#progressText').textContent=`Pasul ${n} din ${steps.length}`;$('#progressFill').style.width=`${n/steps.length*100}%`;$('.progress-track').setAttribute('aria-valuenow',n);if(push)history.pushState({step},'',`?step=${step}`);const h=$(`[data-step-panel="${step}"] h2`);if(h){h.tabIndex=-1;h.focus({preventScroll:true})}window.scrollTo({top:0,behavior:'smooth'});}
  function bind(){
    $$('.step-link').forEach(b=>b.onclick=()=>show(b.dataset.step));
    $$('[data-next]').forEach(b=>b.onclick=()=>show(b.dataset.next));
    addEventListener('popstate',()=>show(new URLSearchParams(location.search).get('step'),false));
    $('#quizList').onchange=e=>{if(e.target.name?.startsWith('q')){state.quiz[+e.target.name.slice(1)]=+e.target.value;state.verify.quiz=false;save();render()}};
    $('#quizForm').onsubmit=e=>{e.preventDefault();state.verify.quiz=true;save();render()};
    $('#resetQuiz').onclick=()=>{state.quiz=[];state.verify.quiz=false;save();render()};
    $('#traitsChoices').onchange=e=>{state.traits=$$('#traitsChoices input:checked').map(x=>+x.value).slice(0,5);render();save();if(state.traits.length<3)feedback('#traitsFeedback','Alege cel puțin 3 trăsături.','error');else feedback('#traitsFeedback','Personajul tău începe să prindă viață!')};
    $('#wishChoices').onchange=e=>{state.wish=wishes[+e.target.value];save()};$('#wishText').oninput=e=>{state.wishText=e.target.value;save()};
    $('#fearChoices').onchange=e=>{state.fear=fears[+e.target.value];save()};$('#fearText').oninput=e=>{state.fearText=e.target.value;save()};
    $('#dialogueList').oninput=e=>{if(e.target.dataset.dialogue){state.dialogues[+e.target.dataset.dialogue]=e.target.value;save()}};
    bindSort();bindPortrait();
    $('#guessList').onclick=e=>{const verifyGuess=e.target.closest('[data-action="check-guess"]');if(verifyGuess){state.verify.guess=true;save();render()}};
    $('#resetAll').onclick=()=>{if(confirm('Sigur vrei să ștergi răspunsurile?')){localStorage.removeItem(KEY);location.reload()}};
  }
function bindSort(){const bank=$('#traitsBank');bank.onclick=e=>{const b=e.target.closest('[data-trait]');if(b){state.sort[b.dataset.trait]=state.sort[b.dataset.trait]==='good'?'bad':'good';renderSort();save();checkSort()}};$$('.drop-zone').forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=e=>{const x=e.dataTransfer.getData('text/plain');if(x){state.sort[x]=z.dataset.zone;renderSort();save();checkSort()}}});$$('.drop-item').forEach(b=>b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.trait||b.dataset.placed));}
  function checkSort(){if(Object.keys(state.sort).length===sort.length){state.verify.sort=true;save();renderSort();const ok=sort.every(([x,z])=>state.sort[x]===z);feedback('#qualityFeedback',ok?'🎉 Bravo! Personajele interesante nu trebuie să fie perfecte. Și eroii pot avea defecte!':'Unele cuvinte au ajuns în categoria greșită. Roșu = categorie greșită; mută cartonașul și verifică din nou.',ok?'success':'error')}}
  function bindPortrait(){const p=state.portrait=state.portrait||{};$('#portraitForm').oninput=e=>{if(e.target.id==='name')p.name=e.target.value;if(e.target.id==='likesOther')p.other=e.target.value;if(e.target.id==='bigWish')p.bigWish=e.target.value;save();summary()};$('#portraitForm').onchange=e=>{if(e.target.name?.startsWith('guess')){p[e.target.name]=+e.target.value;state.verify.guess=false}if(e.target.name==='kindChoices')p.kind=['Copil','Animal','Robot','Creatură fantastică','Extraterestru','Personaj inventat'][+e.target.value];if(e.target.name==='portraitTraits'){p.traits=$$('#portraitTraits input:checked').map(x=>+x.value).slice(0,3);if($$('#portraitTraits input:checked').length>3)e.target.checked=false}if(e.target.name==='likesChoices')p.like=['Aventurile','Animalele','Cărțile','Jocurile','Să exploreze','Să inventeze lucruri','Să ajute oamenii','Altceva'][+e.target.value];if(e.target.name==='portraitFear')p.pfear=fears[+e.target.value];save();renderPortrait()};}
function install(){let d;addEventListener('beforeinstallprompt',e=>{e.preventDefault();d=e;$('#installBtn').hidden=false;$('#installHint').hidden=true});$('#installBtn').onclick=async()=>{if(d){d.prompt();await d.userChoice;d=null;$('#installBtn').hidden=true}};if(!matchMedia('(display-mode:standalone)').matches)$('#installHint').hidden=false;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
render();bind();$$('[data-step-panel="story"] [data-next]').forEach(b=>b.addEventListener('click',()=>{try{localStorage.setItem('after-school-lectia-2-story','read')}catch{}}));install();show(new URLSearchParams(location.search).get('step')||'story',false);
})();

